# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
  sqs:
    image: softwaremill/elasticmq
    restart: always
    ports:
      - '9324:9324'
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - '8000:8000'
