version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0
  sonarcloud: socialtables/sonarcloud@1.1.1

executors:
  node:
    docker:
      - image: circleci/node:lts

jobs:
  lint:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: NPM install
          command: |
            echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ./.npmrc
            npm i
      - save_cache:
          key: dependency-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run lint

  test:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: NPM install
          command: |
            echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ./.npmrc
            npm i
      - run: npm run test:ci
      - run: npm run build
      - sonarcloud/scan-on-branch-commit:
          github-project-slug: first-line-outsourcing/flo.sls
          project-key: first-line-outsourcing_flo.sls
          covered-code-language: typescript

workflows:
  version: 2.1
  lint_and_test:
    jobs:
      - lint
      - test
